spring:
  application:
    name: orbit-web
  datasource:
    url: jdbc:postgresql://localhost:5432/orbit_web
    username: orbit
    password: orbit
  jpa:
    open-in-view: false # do not show inner SQL
    hibernate:
      ddl-auto: validate # just validate do not create schema based on entities

  jackson:
    deserialization:
      fail-on-unknown-properties: true

logging:
  pattern:
    level: "%5p [requestId:%X{requestId:-}]"
server:
  port: 8080
